### PR TITLE
Add check for when number of deleted is None

### PR DESCRIPTION
**Pull request by iveqy**

### CODE REVIEW

**Comment by quentinsf** [comment]
Hi there - thanks for this - it all looks fine, but I'm curious about when you're seeing this as a problem?

I think, if there are no deleted messages, the response that should come back check_response(server.search(None, 'DELETED')) from  is a list containing an empty string [""]. 

I don't think it should ever be None, unless there's a bug in imaplib or in the server?

If this is a reproducible problem for a commonly-used server, we should certainly cater to it, but it may indicate that imaplib is having problems and giving unreliable information for your server?  In which case it would be better to solve it there.

But I may be missing something!

**Comment by iveqy** [comment]
I tried this tool for an account that where using SmarterMail https://www.smartertools.com/smartermail/business-email-server

The return I got was None and not "". I'm not sure why and haven't investigated it any further.

Thanks for a really good tool. It worked flawless and was very easy to use.

**Comment by quentinsf** [comment]
Ah - I had forgotten - you're not the first person to have this problem with SmarterMail:

https://github.com/quentinsf/IMAPdedup/issues/24

Unless that's also you under another name :-)

Could you try the debug option I suggested there, and see if it tells us anything more?

**Comment by tonimelisma** [comment]
Hey @quentinsf,

thanks a lot for a great tool! I'm having the same issue with my icloud (Apple) email, with any folder I try. It lists all the folders properly but even a dry run on a 30-message inbox folder produces the same error. Here's the output with imaplib.Debug = 4:

```
  11:04.85 imaplib version 2.58
  11:04.85 new IMAP4 connection, tag=EHFO
  11:05.04 < * OK [CAPABILITY pv50p00im-tygg10010601 1913B48 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (1913B48-10000-1913B-0-9cb09718163b:1991) pv50p00im-tygg10010601 [16:1610:12:11:04:D0]
  11:05.04 > EHFO0 CAPABILITY
  11:05.23 < * CAPABILITY pv50p00im-tygg10010601 1913B48 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN 
  11:05.23 < EHFO0 OK !!
  11:05.23 CAPABILITIES: ('PV50P00IM-TYGG10010601', '1913B48', 'XAPPLEPUSHSERVICE', 'IMAP4', 'IMAP4REV1', 'SASL-IR', 'AUTH=ATOKEN', 'AUTH=PLAIN')
  11:05.23 > EHFO1 LOGIN "my.obfuscated.login@icloud.com" "my-obfuscated-password"
  11:05.48 < EHFO1 OK User my.obfuscated.login logged in
  11:05.48 > EHFO2 EXAMINE Archive
  11:05.72 < * 37989 EXISTS
  11:05.72 < * OK [UIDVALIDITY 7]
  11:05.72 < * OK [UIDNEXT 38107]
  11:05.72 < * FLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk)
  11:05.72 < * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk \*)]
  11:05.72 < EHFO2 OK [READ-ONLY] EXAMINE completed (took 15 ms)
There are 37989 messages in Archive.
  11:05.72 > EHFO3 SEARCH DELETED
  11:05.97 < EHFO3 OK SEARCH completed (took 27 ms)
  11:05.97 > EHFO4 LOGOUT
  11:06.19 < * BYE
  11:06.19 BYE response: 
Traceback (most recent call last):
  File "imapdedup.py", line 325, in <module>
    main(sys.argv[1:])
  File "imapdedup.py", line 322, in main
    process(options, mboxes)
  File "imapdedup.py", line 234, in process
    deleted = check_response(server.search(None, 'DELETED'))[0].split()
AttributeError: 'NoneType' object has no attribute 'split'
```

So on about line 233 where you check how many messages are marked deleted, first item in the array returned by check_response is NoneType which is invalid input for the split() function.

I'll try debugging more later in the coming days as I have more time. Is there anything simple I can try?

Thanks again for the tool!

**Comment by tonimelisma** [comment]
So checking the second item in the array coming from imaplib's server.search() it seems you're expecting to get an empty array when there's no deleted messages but the function in question actually returns an object of type None.

You're using server.search() a lot with the incorrect assumption but it only fails when the search is empty. Upon quick browsing you're looking for deleted messages at least twice and undeleted ones once with the incorrect assumption.

Here's a quick patch:

tonimelisma@Tonis-MacBook-Pro IMAPdedup % diff -u imapdedup.py.orig imapdedup.py
```
--- imapdedup.py.orig	2019-12-06 14:10:48.000000000 +0200
+++ imapdedup.py	2019-12-06 14:50:20.000000000 +0200
@@ -230,8 +230,8 @@
             print("There are %d messages in %s." % (int(msgs), mbox))
 
             # Check how many messages are already marked 'deleted'...
-            deleted = check_response(server.search(None, 'DELETED'))[0].split()
-            numdeleted = len(deleted)
+            deleted = check_response(server.search(None, 'DELETED'))[0]
+            numdeleted = len(deleted.split()) if deleted else 0
             print("%s message(s) currently marked as deleted in %s" % (numdeleted or "No", mbox))
 
             # ...and get a list of the ones that aren't deleted. That's what we'll use.
@@ -304,10 +304,13 @@
                         if options.verbose:
                             print("Batch starting at item %d marked." % i)
                     print("Confirming new numbers...")
-                    deleted = check_response(server.search(None, 'DELETED'))[0].split()
-                    numdeleted = len(deleted)
-                    undeleted = check_response(server.search(None, 'UNDELETED'))[0].split()
-                    numundel = len(undeleted)
+
+		    deleted = check_response(server.search(None, 'DELETED'))[0]
+                    numdeleted = len(deleted.split()) if deleted else 0
+
+                    undeleted = check_response(server.search(None, 'UNDELETED'))[0]
+                    numundel = len(undeleted.split()) if undeleted else 0
+
                     print("There are now %s messages marked as deleted and %s others in %s." % (numdeleted, numundel, mbox))
         if not options.no_close:
             server.close()

```

**Pull request merged**
